title: Don't collide!
hero_image: images/banner.png
description: Build an endless runner game where your character must avoid colliding with obstacles
version: 4
listed: false
copyedit: false
last_tested: "2024-06-11"
steps:
  - title: Choose a background colour
  - title: Add a player
  - title: Make the player follow the mouse
  - title: Create an obstacle
  - title: Move the obstacle
  - title: Wrap around
  - title: Random obstacle position
  - title: Lots of obstacles
  - title: Collisions
  - title: Finish the game
  - title: What next?
