
title: Don't collide!
hero_image: images/banner.png
description:
  Build an endless runner game where your character must avoid colliding
  with obstacles
meta_title: Python coding projects for kids and teens | Don't collide!
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Build a scrolling runner game in Python and avoid obstacles.
version: 4
listed: false
copyedit: false
last_tested: "2024-06-06"
steps:
  - title: You will make
  - title: Set the theme
  - title: Create obstacles
    completion:
      - engaged
  - title: Collision detection
  - title: Speed up!
    completion:
      - internal
  - title: Upgrade your project
  - title: Share
  - title: something
  - title: something else
